#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export EDITOR=vim
export VISUAL=${EDITOR}

autoload bashcompinit

## Base16 Shell color themes.
# possible themes: 3024, apathy, ashes, atelierdune, atelierforest, atelierhearth,
# atelierseaside, bespin, brewer, chalk, codeschool, colors, default, eighties,
# embers, flat, google, grayscale, greenscreen, harmonic16, isotope, londontube,
# marrakesh, mocha, monokai, ocean, paraiso, pop (dark only), railscasts, shapesifter,
# solarized, summerfruit, tomorrow, twilight
#theme="monokai"
# Possible variants: dark and light
#shade="dark"
#BASE16_SHELL="/usr/share/zsh/scripts/base16-shell/base16-$theme.$shade.sh"
#[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

[[ -f ~/.dir_colors   ]] && match_lhs="${match_lhs}$(<~/.dir_colors)"

# Customize to your needs...

setopt AUTO_CD

setopt MULTIOS

setopt AUTO_NAME_DIRS

setopt GLOB_COMPLETE

setopt RM_STAR_WAIT

setopt ZLE

setopt NO_HUP

setopt NO_CLOBBER
setopt NO_CASE_GLOB

setopt NUMERIC_GLOB_SORT

setopt EXTENDED_GLOB

setopt RC_EXPAND_PARAM

bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

bindkey -M viins ' ' magic-space

bashcompinit
[ -x "$(command -v pandoc)" ] && eval "$(pandoc --bash-completion)"

[[ -f ~/.aliases ]] && source ~/.aliases

